In [79]:
#import libaries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [80]:
# creating a dataset
data = {
    "Roll_No": list(range(101, 131)),

    "Name": [
        "Rahul", "Priya", "Arjun", "Sneha", "Kiran",
        "Anjali", "Vikram", "Pooja", "Rohit", "Divya",
        "Aditya", "Keerthi", "Sai", "Harsha", "Nikhil",
        "Sanjana", "Varun", "Meghana", "Akash", "Swathi",
        "Manoj", "Lavanya", "Karthik", "Deepa", "Surya",
        "Neha", "Abhishek", "Teja", "Rakesh", "Bhavana"
    ],

    "CGPA": [
        8.7, 7.2, 9.1, 6.8, 8.4,
        7.5, 9.3, 6.9, 8.1, 7.8,
        9.0, 7.1, 8.8, 6.5, 8.6,
        7.7, 9.2, 7.0, 8.3, 6.7,
        8.9, 7.4, 9.4, 6.9, 8.2,
        7.6, 9.1, 7.3, 8.5, 6.6
    ],

    "Skills": [
        8, 5, 9, 3, 7,
        6, 9, 4, 7, 6,
        8, 5, 8, 3, 7,
        6, 9, 4, 7, 3,
        8, 5, 9, 4, 7,
        6, 8, 5, 1, 3
    ],

    "Projects": [
        3, 1, 4, 0, 3,
        2, 4, 1, 2, 2,
        3, 1, 3, 0, 3,
        2, 4, 1, 2, 1,
        3, 2, 4, 1, 3,
        2, 3, 1, 0, 0
    ],

    "Internships": [
        1, 0, 2, 0, 1,
        1, 2, 0, 1, 0,
        1, 0, 1, 0, 1,
        1, 2, 0, 1, 0,
        1, 1, 2, 0, 1,
        1, 1, 0, 0, 0
    ],

    "Certifications": [
        4, 2, 5, 1, 3,
        2, 5, 1, 3, 2,
        4, 2, 4, 1, 3,
        3, 5, 1, 3, 1,
        4, 2, 5, 1, 3,
        2, 4, 2, 0, 1
    ],

    "DSA_Score": [
        82, 61, 91, 48, 76,
        68, 94, 52, 74, 65,
        86, 59, 81, 45, 78,
        70, 92, 50, 73, 55,
        84, 63, 95, 49, 77,
        69, 88, 60, 22, 47
    ],

    "Placed": [
        1, 0, 1, 0, 1,
        0, 1, 0, 1, 0,
        1, 0, 1, 0, 1,
        0, 1, 0, 1, 0,
        1, 0, 1, 0, 1,
        0, 1, 0, 0, 0
    ]
}

In [81]:
df = pd.DataFrame(data)

In [82]:
df.head()

   Roll_No   Name  CGPA  Skills  ...  Internships  Certifications  DSA_Score  Placed
0      101  Rahul   8.7       8  ...            1               4         82       1
1      102  Priya   7.2       5  ...            0               2         61       0
2      103  Arjun   9.1       9  ...            2               5         91       1
3      104  Sneha   6.8       3  ...            0               1         48       0
4      105  Kiran   8.4       7  ...            1               3         76       1

[5 rows x 9 columns]

In [83]:
#Creating a dataframe
df

    Roll_No      Name  CGPA  ...  Certifications  DSA_Score  Placed
0       101     Rahul   8.7  ...               4         82       1
1       102     Priya   7.2  ...               2         61       0
2       103     Arjun   9.1  ...               5         91       1
3       104     Sneha   6.8  ...               1         48       0
4       105     Kiran   8.4  ...               3         76       1
5       106    Anjali   7.5  ...               2         68       0
6       107    Vikram   9.3  ...               5         94       1
7       108     Pooja   6.9  ...               1         52       0
8       109     Rohit   8.1  ...               3         74       1
9       110     Divya   7.8  ...               2         65       0
10      111    Aditya   9.0  ...               4         86       1
11      112   Keerthi   7.1  ...               2         59       0
12      113       Sai   8.8  ...               4         81       1
13      114    Harsha   6.5  ...               1         45       0
14      115    Nikhil   8.6  ...               3         78       1
15      116   Sanjana   7.7  ...               3         70       0
16      117     Varun   9.2  ...               5         92       1
17      118   Meghana   7.0  ...               1         50       0
18      119     Akash   8.3  ...               3         73       1
19      120    Swathi   6.7  ...               1         55       0
20      121     Manoj   8.9  ...               4         84       1
21      122   Lavanya   7.4  ...               2         63       0
22      123   Karthik   9.4  ...               5         95       1
23      124     Deepa   6.9  ...               1         49       0
24      125     Surya   8.2  ...               3         77       1
25      126      Neha   7.6  ...               2         69       0
26      127  Abhishek   9.1  ...               4         88       1
27      128      Teja   7.3  ...               2         60       0
28      129    Rakesh   8.5  ...               0         22       0
29      130   Bhavana   6.6  ...               1         47       0

[30 rows x 9 columns]

In [84]:
#select the features
# Roll number and Name are nor used for predection
X = df[
    ["CGPA",
     "Skills",
     "Projects",
     "Internships",
     "Certifications",
     "DSA_Score"
     ]
]

In [85]:
X

    CGPA  Skills  Projects  Internships  Certifications  DSA_Score
0    8.7       8         3            1               4         82
1    7.2       5         1            0               2         61
2    9.1       9         4            2               5         91
3    6.8       3         0            0               1         48
4    8.4       7         3            1               3         76
5    7.5       6         2            1               2         68
6    9.3       9         4            2               5         94
7    6.9       4         1            0               1         52
8    8.1       7         2            1               3         74
9    7.8       6         2            0               2         65
10   9.0       8         3            1               4         86
11   7.1       5         1            0               2         59
12   8.8       8         3            1               4         81
13   6.5       3         0            0               1         45
14   8.6       7         3            1               3         78
15   7.7       6         2            1               3         70
16   9.2       9         4            2               5         92
17   7.0       4         1            0               1         50
18   8.3       7         2            1               3         73
19   6.7       3         1            0               1         55
20   8.9       8         3            1               4         84
21   7.4       5         2            1               2         63
22   9.4       9         4            2               5         95
23   6.9       4         1            0               1         49
24   8.2       7         3            1               3         77
25   7.6       6         2            1               2         69
26   9.1       8         3            1               4         88
27   7.3       5         1            0               2         60
28   8.5       1         0            0               0         22
29   6.6       3         0            0               1         47

In [86]:
# slect the target /label (y)
y = df["Placed"]

In [87]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    0
29    0
Name: Placed, dtype: int64

In [88]:
#6 splitting the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, # 20% test data
    random_state=42 # Random number
)

In [89]:
print("Training students:",len(X_train))
print("Testing students:",len(X_test))

Training students: 24
Testing students: 6

Creating the model for the project

In [90]:
model = DecisionTreeClassifier(random_state=42)

Train the model

In [91]:
model.fit(X_train, y_train)
print('\nModel Trained Successfully')

Model Trained Successfully

Test the model

In [92]:
Guessing = model.predict(X_test)
print('\nActual Values', list(y_test))
print('\nPredicted Values', list(Guessing))

Actual Values [0, 0, 0, 0, 1, 0]

Predicted Values [np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0)]

Testing Accuracy

In [93]:
accuracy = accuracy_score(y_test, Guessing)
print('\nAccuracyscore', accuracy)

Accuracyscore 0.8333333333333334

In [99]:
from sklearn.metrics import classification_report

# Generate and print the classification report
report = classification_report(y_test, Guessing, target_names=['Not Placed', 'Placed'])
print("Classification Report:\n")
print(report)

Classification Report:

              precision    recall  f1-score   support

  Not Placed       1.00      0.80      0.89         5
      Placed       0.50      1.00      0.67         1

    accuracy                           0.83         6
   macro avg       0.75      0.90      0.78         6
weighted avg       0.92      0.83      0.85         6

Creating a new Data

In [94]:
#creating a completely new student
new_student = pd.DataFrame([{
    "CGPA":8.5,
    "Skills": 3,
    "Projects": 2,
    "Internships": 1,
    "Certifications": 3,
    "DSA_Score": 82
}])

New Student

In [95]:
new_student

   CGPA  Skills  Projects  Internships  Certifications  DSA_Score
0   8.5       3         2            1               3         82

Predicting the new student output

In [96]:
prediction = model.predict(new_student)
print('\nPrediction:', prediction)

Prediction: [1]

if else statement to  Displey the predection

In [97]:
if prediction[0] ==1:
  print('\nStudent will be Placed🎉')
else:
  print('\nStudent will not be 😓')

Student will be Placed🎉